[build-system]
# Informa ao pip que ele precisa do setuptools para construir o pacote
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "automatizador-git-linkedin"
version = "0.1.0"
description = "Um script para automatizar a criação de posts e repositórios no GitHub."
requires-python = ">=3.13"
dependencies = [
    "groq>=0.33.0",
    "python-dotenv>=1.2.1",
]

[project.scripts]
# Esta é a parte que cria o comando "meu-app" que o run.py procura.
# Ela aponta para: pacote 'automatizador', arquivo 'main', função 'iniciar_aplicacao'
meu-app = "automatizador.main:iniciar_aplicacao"
